# Housing Market

### Introduction:

This time we will create our own dataset with fictional numbers to describe a house market. As we are going to create random data don't try to reason of the numbers.

### Step 1. Import the necessary libraries

In [6]:
import pandas as pd
import numpy as np
import random as rd

### Step 2. Create 3 differents Series, each of length 100, as follows: 
1. The first a random number from 1 to 4 
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000

In [38]:
a = np.random.randint(low=1, high=4, size=100)
b = np.random.randint(low=1, high=3, size=100)
c = np.random.randint(low=10000, high=30000, size=100)
a, b, c

(array([1, 3, 2, 1, 1, 3, 2, 1, 3, 2, 1, 3, 1, 2, 1, 2, 3, 1, 3, 2, 2, 1,
        2, 1, 1, 2, 1, 3, 2, 3, 2, 3, 3, 2, 3, 1, 2, 1, 3, 1, 2, 2, 2, 2,
        3, 3, 3, 3, 1, 3, 3, 3, 1, 1, 3, 2, 1, 2, 3, 1, 3, 3, 3, 2, 2, 2,
        1, 1, 1, 1, 2, 1, 2, 1, 1, 2, 3, 3, 1, 2, 1, 3, 2, 2, 2, 2, 3, 3,
        3, 1, 1, 2, 1, 3, 1, 1, 1, 2, 1, 3]),
 array([2, 1, 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 1, 1, 2,
        1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2, 2, 1, 2, 1,
        1, 2, 1, 1, 2, 2, 1, 1, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2,
        2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 2, 2, 1,
        2, 1, 2, 2, 1, 1, 2, 1, 2, 1, 1, 1]),
 array([27939, 15060, 19080, 20520, 23946, 19810, 22061, 20148, 14463,
        23068, 21095, 11891, 28262, 15711, 17541, 13647, 11319, 16297,
        25217, 16095, 17482, 20516, 22765, 29305, 27291, 10264, 24825,
        16784, 14812, 13751, 20108, 19627, 12667, 28997, 21204, 21733,
        12767, 12252, 25905, 143

### Step 3. Let's create a DataFrame by joinning the Series by column

In [45]:
numbers = pd.DataFrame(np.column_stack([a, b, c]), columns=['0', '1', '2'])
numbers

0  1      2
0   1  2  27939
1   3  1  15060
2   2  1  19080
3   1  2  20520
4   1  1  23946
.. .. ..    ...
95  1  1  17684
96  1  2  18612
97  2  1  12675
98  1  1  12862
99  3  1  25658

[100 rows x 3 columns]

### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter

In [47]:
numbers2 = numbers.set_axis(['bedrs', 'bathrs', 'price_sqr_meter'], axis=1)
numbers2

bedrs  bathrs  price_sqr_meter
0       1       2            27939
1       3       1            15060
2       2       1            19080
3       1       2            20520
4       1       1            23946
..    ...     ...              ...
95      1       1            17684
96      1       2            18612
97      2       1            12675
98      1       1            12862
99      3       1            25658

[100 rows x 3 columns]

### Step 5. Create a one column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

In [60]:
numbers3 = pd.concat([numbers2["bedrs"], numbers2['bathrs'], numbers2['price_sqr_meter']])
numbers3

0         1
1         3
2         2
3         1
4         1
      ...  
95    17684
96    18612
97    12675
98    12862
99    25658
Length: 300, dtype: int32

### Step 6. Oops, it seems it is going only until index 99. Is it true?

In [61]:

len(numbers3)

300

### Step 7. Reindex the DataFrame so it goes from 0 to 299

0
0        2
1        2
2        4
3        2
4        1
5        1
6        2
7        3
8        3
9        2
10       1
11       2
12       4
13       1
14       2
15       3
16       4
17       4
18       4
19       3
20       2
21       1
22       4
23       1
24       3
25       2
26       3
27       1
28       3
29       4
..     ...
270  23963
271  26782
272  11199
273  23600
274  26935
275  27365
276  23084
277  19052
278  19922
279  17088
280  25468
281  10924
282  10243
283  19834
284  21288
285  22410
286  22348
287  18812
288  29522
289  20838
290  28695
291  23000
292  21684
293  26316
294  10866
295  12337
296  13480
297  25158
298  25585
299  26142

[300 rows x 1 columns]